package net.minecraft.world.level.dimension.special;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;

public class ColoredBlocks {
	public static final Block[] CARPETS = new Block[]{
		Blocks.WHITE_CARPET,
		Blocks.ORANGE_CARPET,
		Blocks.MAGENTA_CARPET,
		Blocks.LIGHT_BLUE_CARPET,
		Blocks.YELLOW_CARPET,
		Blocks.LIME_CARPET,
		Blocks.PINK_CARPET,
		Blocks.GRAY_CARPET,
		Blocks.LIGHT_GRAY_CARPET,
		Blocks.CYAN_CARPET,
		Blocks.PURPLE_CARPET,
		Blocks.BLUE_CARPET,
		Blocks.BROWN_CARPET,
		Blocks.GREEN_CARPET,
		Blocks.RED_CARPET,
		Blocks.BLACK_CARPET
	};
	public static final Block[] WOOLS = new Block[]{
		Blocks.WHITE_WOOL,
		Blocks.ORANGE_WOOL,
		Blocks.MAGENTA_WOOL,
		Blocks.LIGHT_BLUE_WOOL,
		Blocks.YELLOW_WOOL,
		Blocks.LIME_WOOL,
		Blocks.PINK_WOOL,
		Blocks.GRAY_WOOL,
		Blocks.LIGHT_GRAY_WOOL,
		Blocks.CYAN_WOOL,
		Blocks.PURPLE_WOOL,
		Blocks.BLUE_WOOL,
		Blocks.BROWN_WOOL,
		Blocks.GREEN_WOOL,
		Blocks.RED_WOOL,
		Blocks.BLACK_WOOL
	};
	public static final Block[] STAINED_GLASS = new Block[]{
		Blocks.WHITE_STAINED_GLASS,
		Blocks.ORANGE_STAINED_GLASS,
		Blocks.MAGENTA_STAINED_GLASS,
		Blocks.LIGHT_BLUE_STAINED_GLASS,
		Blocks.YELLOW_STAINED_GLASS,
		Blocks.LIME_STAINED_GLASS,
		Blocks.PINK_STAINED_GLASS,
		Blocks.GRAY_STAINED_GLASS,
		Blocks.LIGHT_GRAY_STAINED_GLASS,
		Blocks.CYAN_STAINED_GLASS,
		Blocks.PURPLE_STAINED_GLASS,
		Blocks.BLUE_STAINED_GLASS,
		Blocks.BROWN_STAINED_GLASS,
		Blocks.GREEN_STAINED_GLASS,
		Blocks.RED_STAINED_GLASS,
		Blocks.BLACK_STAINED_GLASS
	};
	public static final Block[] STAINED_GLASS_PANES = new Block[]{
		Blocks.WHITE_STAINED_GLASS_PANE,
		Blocks.ORANGE_STAINED_GLASS_PANE,
		Blocks.MAGENTA_STAINED_GLASS_PANE,
		Blocks.LIGHT_BLUE_STAINED_GLASS_PANE,
		Blocks.YELLOW_STAINED_GLASS_PANE,
		Blocks.LIME_STAINED_GLASS_PANE,
		Blocks.PINK_STAINED_GLASS_PANE,
		Blocks.GRAY_STAINED_GLASS_PANE,
		Blocks.LIGHT_GRAY_STAINED_GLASS_PANE,
		Blocks.CYAN_STAINED_GLASS_PANE,
		Blocks.PURPLE_STAINED_GLASS_PANE,
		Blocks.BLUE_STAINED_GLASS_PANE,
		Blocks.BROWN_STAINED_GLASS_PANE,
		Blocks.GREEN_STAINED_GLASS_PANE,
		Blocks.RED_STAINED_GLASS_PANE,
		Blocks.BLACK_STAINED_GLASS_PANE
	};
	public static final Block[] TERRACOTTA = new Block[]{
		Blocks.WHITE_TERRACOTTA,
		Blocks.ORANGE_TERRACOTTA,
		Blocks.MAGENTA_TERRACOTTA,
		Blocks.LIGHT_BLUE_TERRACOTTA,
		Blocks.YELLOW_TERRACOTTA,
		Blocks.LIME_TERRACOTTA,
		Blocks.PINK_TERRACOTTA,
		Blocks.GRAY_TERRACOTTA,
		Blocks.LIGHT_GRAY_TERRACOTTA,
		Blocks.CYAN_TERRACOTTA,
		Blocks.PURPLE_TERRACOTTA,
		Blocks.BLUE_TERRACOTTA,
		Blocks.BROWN_TERRACOTTA,
		Blocks.GREEN_TERRACOTTA,
		Blocks.RED_TERRACOTTA,
		Blocks.BLACK_TERRACOTTA
	};
	public static final Block[] GLAZED_TERRACOTTA = new Block[]{
		Blocks.WHITE_GLAZED_TERRACOTTA,
		Blocks.ORANGE_GLAZED_TERRACOTTA,
		Blocks.MAGENTA_GLAZED_TERRACOTTA,
		Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA,
		Blocks.YELLOW_GLAZED_TERRACOTTA,
		Blocks.LIME_GLAZED_TERRACOTTA,
		Blocks.PINK_GLAZED_TERRACOTTA,
		Blocks.GRAY_GLAZED_TERRACOTTA,
		Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA,
		Blocks.CYAN_GLAZED_TERRACOTTA,
		Blocks.PURPLE_GLAZED_TERRACOTTA,
		Blocks.BLUE_GLAZED_TERRACOTTA,
		Blocks.BROWN_GLAZED_TERRACOTTA,
		Blocks.GREEN_GLAZED_TERRACOTTA,
		Blocks.RED_GLAZED_TERRACOTTA,
		Blocks.BLACK_GLAZED_TERRACOTTA
	};
	public static final Block[] CONCRETE = new Block[]{
		Blocks.WHITE_CONCRETE,
		Blocks.ORANGE_CONCRETE,
		Blocks.MAGENTA_CONCRETE,
		Blocks.LIGHT_BLUE_CONCRETE,
		Blocks.YELLOW_CONCRETE,
		Blocks.LIME_CONCRETE,
		Blocks.PINK_CONCRETE,
		Blocks.GRAY_CONCRETE,
		Blocks.LIGHT_GRAY_CONCRETE,
		Blocks.CYAN_CONCRETE,
		Blocks.PURPLE_CONCRETE,
		Blocks.BLUE_CONCRETE,
		Blocks.BROWN_CONCRETE,
		Blocks.GREEN_CONCRETE,
		Blocks.RED_CONCRETE,
		Blocks.BLACK_CONCRETE
	};
	public static final Block[] CONCRETE_POWDERS = new Block[]{
		Blocks.WHITE_CONCRETE_POWDER,
		Blocks.ORANGE_CONCRETE_POWDER,
		Blocks.MAGENTA_CONCRETE_POWDER,
		Blocks.LIGHT_BLUE_CONCRETE_POWDER,
		Blocks.YELLOW_CONCRETE_POWDER,
		Blocks.LIME_CONCRETE_POWDER,
		Blocks.PINK_CONCRETE_POWDER,
		Blocks.GRAY_CONCRETE_POWDER,
		Blocks.LIGHT_GRAY_CONCRETE_POWDER,
		Blocks.CYAN_CONCRETE_POWDER,
		Blocks.PURPLE_CONCRETE_POWDER,
		Blocks.BLUE_CONCRETE_POWDER,
		Blocks.BROWN_CONCRETE_POWDER,
		Blocks.GREEN_CONCRETE_POWDER,
		Blocks.RED_CONCRETE_POWDER,
		Blocks.BLACK_CONCRETE_POWDER
	};
	public static final Block[][] COLORED_BLOCKS = new Block[][]{
		WOOLS, CARPETS, STAINED_GLASS, STAINED_GLASS_PANES, TERRACOTTA, GLAZED_TERRACOTTA, CONCRETE, CONCRETE_POWDERS
	};
}
