@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.recipebook;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;
