@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.resources;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;
