@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.damagesource;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;
