@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.obfuscate;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;
