@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.sounds;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;
