@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.commands.synchronization.brigadier;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;
